Update criarusuario

diff --git a/Modulos/criarusuario b/Modulos/criarusuario
--- a/Modulos/criarusuario
+++ b/Modulos/criarusuario
@@ -250,6 +250,82 @@ fun_edithost() {
         fun_edithost
     fi
 }
+
+
+fun_usertoken() {
+    clear
+    tput setaf 7
+    tput setab 4
+    tput bold
+    printf '%30s%s%-15s\n' "Criar Token SSH"
+    tput sgr0
+    echo ""
+    echo -ne "\033[1;32mInsira o Token:\033[1;37m "
+    read username
+    [[ -z $username ]] && {
+        echo -e "\n${cor1}Token vazio ou invalido!${scor}\n"
+        exit 1
+    }
+    [[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
+        echo -e "\n${cor1}Este Token já existe. tente outro Token!${scor}\n"
+        exit 1
+    }
+    [[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um Token inválido!${scor}"
+        echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
+        exit 1
+    }
+    sizemin=$(echo ${#username})
+    [[ $sizemin -lt 2 ]] && {
+        echo -e "\n${cor1}Você digitou um Token muito curto${scor}"
+        echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+        exit 1
+    }
+    echo -ne "\033[1;32mDias para expirar:\033[1;37m "
+    read dias
+    [[ -z $dias ]] && {
+        echo -e "\n${cor1}Numero de dias vazio!${scor}\n"
+        exit 1
+    }
+    [[ ${dias} != ?(+|-)+([0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um número de dias inválido!${scor}\n"
+        exit 1
+    }
+    [[ $dias -lt 1 ]] && {
+        echo -e "\n${cor1}O número deve ser maior que zero!${scor}\n"
+        exit 1
+    }
+    echo -ne "\033[1;32mLimite de conexões:\033[1;37m "
+    read sshlimiter
+    [[ -z $sshlimiter ]] && {
+        echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
+        exit 1
+    }
+    [[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um número de conexões inválido!${scor}\n"
+        exit 1
+    }
+    [[ $sshlimiter -lt 1 ]] && {
+        echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
+        exit 1
+    }
+    password=$(cat /etc/SSHPlus/Token.txt)
+    final=$(date "+%Y-%m-%d" -d "+$dias days")
+    gui=$(date "+%d/%m/%Y" -d "+$dias days")
+    pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+    useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
+    echo "$password" >/etc/SSHPlus/senha/$username
+    echo "$username $sshlimiter" >>/root/usuarios.db
+    clear
+    echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
+    echo -e "\n\033[1;32mIP: \033[1;37m$IP"
+    echo -e "\033[1;32mToken: \033[1;37m$username"
+    echo -e "\033[1;32mExpira em: \033[1;37m$gui"
+    echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
+
+}
+
+
 [[ ! -e /usr/lib/sshplus ]] && exit 0
 tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-15s\n' "CRIAR USUÁRIO SSH";tput sgr0
 #echo -ne "\033[1;32m📝 NOME:\033[1;37m ";read namee
